package com.bravo.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class jobCategoryObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;

   private java.lang.String iconURL;

   public jobCategoryObject()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getIconURL()
   {
      return this.iconURL;
   }

   public void setIconURL(java.lang.String iconURL)
   {
      this.iconURL = iconURL;
   }

   public String toString()
   {
      String str = "id: " + id;
      str += "  name: " + name;
      str += "  iconURL: " + iconURL;
      return str;
   }

   public jobCategoryObject(java.lang.String name, java.lang.String iconURL)
   {
      this.name = name;
      this.iconURL = iconURL;
   }
}