package com.bravo.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class radioOptions implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String option1;

   private java.lang.String option2;

   public radioOptions()
   {
   }

   public java.lang.String getOption1()
   {
      return this.option1;
   }

   public void setOption1(java.lang.String option1)
   {
      this.option1 = option1;
   }

   public java.lang.String getOption2()
   {
      return this.option2;
   }

   public void setOption2(java.lang.String option2)
   {
      this.option2 = option2;
   }

   public radioOptions(java.lang.String option1, java.lang.String option2)
   {
      this.option1 = option1;
      this.option2 = option2;
   }
    
    public String toString(){
      String str="option 1:"+option1;
      str+="  option 2:"+ option2;
      return str;
   }
}