package com.bravo.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class radioOptions implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> optionTexts;

   public radioOptions()
   {
   }

   public String toString()
   {
      String str = "option 1:" + option1;
      str += "  option 2:" + option2;
      return str;
   }

   public java.util.List<java.lang.String> getOptionTexts()
   {
      return this.optionTexts;
   }

   public void setOptionTexts(java.util.List<java.lang.String> optionTexts)
   {
      this.optionTexts = optionTexts;
   }

   public radioOptions(java.util.List<java.lang.String> optionTexts)
   {
      this.optionTexts = optionTexts;
   }
}