package com.bravo.management;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "USER_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "USER_ID_GENERATOR", sequenceName = "USER_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("שם משתמש")
   private java.lang.String userId;

   @org.kie.api.definition.type.Label("מחלקה")
   private java.lang.String department;

   @org.kie.api.definition.type.Label("נוכחות")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "\u05D6\u05DE\u05DF \u05EA\u05E4\u05D5\u05D2\u05EA \u05EA\u05D5\u05E7\u05E3")
   private java.util.Date shiftExpirationTime;

   public User()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.lang.String getDepartment()
   {
      return this.department;
   }

   public void setDepartment(java.lang.String department)
   {
      this.department = department;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public User(java.lang.String userId,
         java.lang.String department, java.lang.String status,java.util.Date shiftExpirationTime)
   {
      this.userId = userId;
      this.department = department;
      this.status = status;
      this.shiftExpirationTime = shiftExpirationTime;
   }
   

   public User(java.lang.String userId,
         java.lang.String department, java.lang.String status)
   {
      this.userId = userId;
      this.department = department;
      this.status = status;
   }
   

   public java.util.Date getShiftExpirationTime()
   {
      return this.shiftExpirationTime;
   }

   public void setShiftExpirationTime(java.util.Date shiftExpirationTime)
   {
      this.shiftExpirationTime = shiftExpirationTime;
   }

   public User(java.lang.Long id, java.lang.String userId,
         java.lang.String department, java.lang.String status,
         java.util.Date shiftExpirationTime)
   {
      this.id = id;
      this.userId = userId;
      this.department = department;
      this.status = status;
      this.shiftExpirationTime = shiftExpirationTime;
   }
   
   
   
   public String toString(){
       String str="userId:"+userId;
       str+="  department:"+ department;
      str+="  status:"+ status;
      str+="  shiftExpirationTime:"+ shiftExpirationTime;
      return str;
   }

}